#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

hc unlock
hc emit_hook reload

# Scripts directory
HERB=~/.config/herbstluftwm
SCRIPTS=$HERB/scripts

#Set wallpaper/background
feh --bg-fill /home/goober/.config/wallpapers/sakura-femboy.jpg
xsetroot -solid '#B55088'

# Autostart daemons'n'stuff
#zzzfm -d &
#devmon &
#leafpad $HERB/help.txt &
setxkbmap -option caps:swapescape
~/.local/kitty.app/bin/kitty &
picom -i 0.69 --active-opacity 0.69 &
xrdb merge ~/.Xresources

# Setup layout
hc set default_frame_layout grid

# Remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-q close
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-b spawn sudo persist-config --shutdown --command reboot
hc keybind $Mod-Shift-b spawn sudo reboot
hc keybind $Mod-Shift-t spawn sudo shutdown now

# Basic movement in tiling and floating mode
# Focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# Moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# Splitting frames (too accident prone)
# Create an empty frame at the specified direction
#hc keybind $Mod-u       split   bottom  0.5
#hc keybind $Mod-o       split   right   0.5
# Let the current frame explode into subframes
#hc keybind $Mod-Control-space split explode

# Resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# Open apps
hc keybind $Mod-Return spawn ~/.local/kitty.app/bin/kitty
hc keybind $Mod-space spawn dmenu_run
hc keybind $Mod-b spawn qutebrowser

# Screenshots
hc keybind $Mod-F12 spawn scrot -t 20 -d 2 ~/%Y-%m-%d-%T-screenshot.png

# Media volume
hc keybind XF86AudioRaiseVolume spawn ~/.config/herbstluftwm/scripts/volume.sh up
hc keybind XF86AudioLowerVolume spawn  ~/.config/herbstluftwm/scripts/volume.sh down
hc keybind XF86AudioMute spawn ~/.config/herbstluftwm/scripts/volume.sh mute

# Tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )
hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}"
do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if [ -n "$key" ]
    then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done
# Cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# Layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-Control-m jumpto last-minimized
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-Shift-space                                                     \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# Nope!
hc mouseunbind --all                                 # Mouse for pussies >:3

# Focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# Settings
hc set smart_window_surroundings off
hc set smart_frame_surroundings on                   # Somehow this fixed some error?
hc set frame_bg_transparent on                       # Ensure window gaps fully expose background
hc set frame_active_opacity 69                       # We love to see some cutesy background
hc set frame_normal_opacity 69                       # Gotta remind everyone who they're dealin wit
hc set window_gap 12                                 # Cause ricing trend
hc set frame_gap 0                                   # Gap windows not frames
hc set_layout grid                                   # Grid arranges better in most cases

# Theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc attr theme.title_height 0                         # Fuck off titles
hc attr theme.padding_top 0                          # Nuh-uh
hc attr theme.floating.outer_width 0                 # Again, only one per window

# Borders, cause hot ricing trend
hc attr theme.border_width 4
hc attr theme.outer_width 4
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 4
hc attr theme.active.outer_color '#B55088'
hc attr theme.normal.outer_color '#007F7F'
hc attr theme.floating.outer_color '#FFFFFF'

# Taskbar
hc attr theme.active.color '#B55088'
hc set frame_border_normal_color '#007F7F'

# Rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
hc rule instance="Floating" manage=on floating=on floatplacement=center

# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule class=Gtkdialog floating=on
hc rule class=Wallpaper floating=on
hc rule class="Desktop-session-exit.py" floating=on

# Tree styling
hc set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
#hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(hc list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" "$monitor" &
done
